package org.tvbuttons.free;
import android.app.*;import android.content.*;import android.net.*;import android.os.*;import org.json.*;import java.io.*;
public class AdbBridgeService extends Service implements SharedPreferences.OnSharedPreferenceChangeListener {
 public static volatile AdbBridgeService instance;public static volatile String state="Подключаем управление пультом…";public static volatile int lastKey=-1,lastScan=-1;
 ScreenTools screens;volatile LocalAdb localAdb;volatile boolean running;volatile PrintWriter writer;volatile LocalSocket socket;boolean uiVisible;SharedPreferences prefs;
 public void onCreate(){super.onCreate();screens=new ScreenTools(this);instance=this;uiVisible=MainActivity.screenActive;prefs=getSharedPreferences("buttons",0);prefs.registerOnSharedPreferenceChangeListener(this);NotificationManager nm=getSystemService(NotificationManager.class);nm.createNotificationChannel(new NotificationChannel("adb_bridge","Кнопки пульта",NotificationManager.IMPORTANCE_LOW));startForeground(7,new Notification.Builder(this,"adb_bridge").setSmallIcon(android.R.drawable.ic_media_play).setContentTitle("Управление пультом").setContentText("Отключение доступно в приложении.").build());running=true;new Thread(this::connect,"adb-bridge-client").start();}
 void connect(){while(running){try(LocalSocket s=new LocalSocket()){socket=s;s.connect(new LocalSocketAddress(ShellBridge.SOCKET,LocalSocketAddress.Namespace.ABSTRACT));writer=new PrintWriter(s.getOutputStream(),true);sendConfig();BufferedReader r=new BufferedReader(new InputStreamReader(s.getInputStream(),"UTF-8"));String line;while(running&&(line=r.readLine())!=null){JSONObject j=new JSONObject(line);if(j.has("uiAction")){String a=j.getString("uiAction");if(a.equals("inputs"))new Handler(Looper.getMainLooper()).post(()->startActivity(new Intent(this,InputsActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)));else screens.action(a);}if(j.has("message"))screens.toast(j.getString("message"));if(j.has("status")){String v=j.getString("status");state=v.equals("ACTIVE")?"Управление пультом работает":v.equals("OBSERVING")?"Подключено • в настройках кнопки работают как обычно":v.equals("CONNECTED")?"Пульт подключён":v;}if(j.has("key")){lastKey=j.optInt("key");lastScan=j.optInt("scan");getSharedPreferences("adb_diagnostics",0).edit().putInt("scan",lastScan).putInt("key",lastKey).putInt("value",j.optInt("value")).putLong("time",System.currentTimeMillis()).apply();}}}catch(Exception ignored){}finally{writer=null;socket=null;}if(!running)break;try{state="Восстанавливаем управление пультом…";startHelper();}catch(Exception e){getSharedPreferences("adb_diagnostics",0).edit().putString("startup_error",e.toString()).apply();android.util.Log.w("TVButtons","Local ADB startup failed: "+e.getClass().getSimpleName()+": "+e.getMessage());state=e instanceof java.net.ConnectException?"ADB на ТВ недоступен. Включи отладку по сети":e instanceof java.net.SocketTimeoutException?"Ожидаем разрешения ADB или ответа ТВ…":"Повторяем запуск помощника…";}try{Thread.sleep(5000);}catch(InterruptedException ignored){}}}
 void startHelper()throws Exception {try(LocalAdb adb=new LocalAdb(this)){localAdb=adb;adb.connect();String identity=adb.shell("id");if(identity.contains("uid=0(")){state="Переключаем ADB в обычный режим…";try{adb.unroot();}catch(java.io.IOException expected){}return;}if(!identity.contains("uid=2000("))throw new java.io.IOException("ADB shell required");if(!running)return;String base="/data/local/tmp/tvbuttons-auto-"+getPackageManager().getPackageInfo(getPackageName(),0).versionCode;String apk=base+".apk",nativePath=base+"-events";String ready=adb.shell("test -s "+apk+" && test -x "+nativePath+" && echo READY");if(!ready.contains("READY")){try(java.io.FileInputStream file=new java.io.FileInputStream(getApplicationInfo().sourceDir)){adb.push(file,apk);}try(java.io.InputStream file=getAssets().open("tvbuttons-events")){adb.push(file,nativePath);}adb.shell("chmod 700 "+nativePath);}if(!running)return;String command="setsid env CLASSPATH="+apk+" app_process /system/bin org.tvbuttons.free.ShellBridge "+android.os.Process.myUid()+" --events "+nativePath+" >/data/local/tmp/tvbuttons-bridge.log 2>&1 </dev/null & sleep 1";adb.shell(command);android.util.Log.i("TVButtons","Local ADB helper launched as shell");}finally{localAdb=null;}}
 synchronized void sendConfig(){if(writer==null)return;try{JSONObject maps=new JSONObject(),scans=new JSONObject();for(String s:prefs.getAll().keySet()){if(s.startsWith("map.")){String[] parts=s.split("\\.");if(parts.length==3){JSONObject row=maps.optJSONObject(parts[1]);if(row==null){row=new JSONObject();maps.put(parts[1],row);}row.put(parts[2],prefs.getString(s,""));}}else if(s.startsWith("scan."))scans.put(s.substring(5),prefs.getInt(s,-1));}android.util.DisplayMetrics metrics=new android.util.DisplayMetrics();getSystemService(android.view.WindowManager.class).getDefaultDisplay().getRealMetrics(metrics);writer.println(new JSONObject().put("width",metrics.widthPixels).put("height",metrics.heightPixels).put("enabled",(prefs.getBoolean("enabled",true)&&ControlMode.adb(this))).put("uiVisible",uiVisible).put("maps",maps).put("scans",scans).put("deviceName",prefs.getString("remote_device","input_btrcu")).toString());}catch(Exception ignored){}}
 public synchronized void visible(boolean value){uiVisible=value;sendConfig();}public synchronized boolean action(String a){if(ControlMode.adb(this)&&ControlMode.enabled(this)&&writer!=null)try{writer.println(new JSONObject().put("action",a).toString());return !writer.checkError();}catch(Exception ignored){}return false;}
 public void onSharedPreferenceChanged(SharedPreferences p,String key){sendConfig();if(!ControlMode.adb(this)||!ControlMode.enabled(this))stopSelf();}public int onStartCommand(Intent i,int flags,int id){if(!ControlMode.adb(this)||!prefs.getBoolean("enabled",true)){stopSelf();return START_NOT_STICKY;}return START_STICKY;}public IBinder onBind(Intent i){return null;}
 public void onDestroy(){running=false;screens.close();try{if(localAdb!=null)localAdb.close();}catch(Exception ignored){}prefs.unregisterOnSharedPreferenceChangeListener(this);try{if(socket!=null)socket.close();}catch(Exception ignored){}instance=null;state="Управление пультом выключено";super.onDestroy();}
}
