package org.tvbuttons.free;
import android.view.*;import android.os.*;import android.util.Base64;import org.json.*;import java.util.concurrent.*;import java.util.regex.*;
final class BridgeActions {
 final ShellBridge bridge;final ExecutorService jobs=Executors.newSingleThreadExecutor();final ScheduledExecutorService history=Executors.newSingleThreadScheduledExecutor();volatile String current="",previous="";volatile boolean mouse,black;int x=960,y=540;
 BridgeActions(ShellBridge b){bridge=b;history.scheduleWithFixedDelay(()->{try{foreground();}catch(Exception ignored){}},1,2,TimeUnit.SECONDS);}
 String foreground()throws Exception {String text=bridge.command("dumpsys","activity","activities");Matcher m=Pattern.compile("mResumedActivity:.*? u0 ([a-zA-Z0-9_.]+)/").matcher(text);if(m.find()){String pkg=m.group(1);if(!pkg.equals("org.tvbuttons.free")&&!pkg.equals(current)){previous=current;current=pkg;}return pkg;}return "";}
 boolean protectedApp(String pkg){return pkg.isEmpty()||pkg.equals("android")||pkg.equals("org.tvbuttons.free")||pkg.startsWith("com.android.")||pkg.startsWith("com.yandex.tv.")||pkg.startsWith("com.droidlogic.");}
 void submit(String action){jobs.submit(()->{try{run(action);}catch(Exception e){bridge.message("Не удалось выполнить «"+ActionCatalog.label(action)+"»");System.err.println("Action failed: "+action.split(":",2)[0]+": "+e.getClass().getSimpleName());}});}
 void run(String a)throws Exception {
  if(a.equals("previous")){foreground();String target=previous;if(target.isEmpty()){bridge.message("Предыдущее приложение пока не известно");return;}bridge.launchApp(target);return;}
  if(a.equals("closeapp")||a.equals("restartapp")){String target=foreground();if(protectedApp(target)){bridge.message("Системные компоненты ТВ не закрываем");return;}bridge.command("am","force-stop","--user","0",target);if(a.equals("restartapp"))bridge.launchApp(target);return;}
  if(a.equals("settings")){start("android.settings.SETTINGS");return;}if(a.equals("wifi")){start("android.settings.WIFI_SETTINGS");return;}
  if(a.equals("bluetooth")){component("com.android.tv.settings/.accessories.AddAccessoryActivity");return;}
  if(a.equals("picture")){component("com.yandex.tv.settings/.display.DisplayActivity");return;}if(a.equals("sound")){component("com.yandex.tv.settings/.sound.SoundActivity");return;}
  if(a.equals("alice")){check(bridge.command("am","start","-a","android.intent.action.ASSIST","-n","com.yandex.tv.alice/.app.AliceGatewayActivity"));return;}
  if(a.startsWith("hdmi:")){int port=Integer.parseInt(a.substring(5));if(port<1||port>3)throw new IllegalArgumentException();tapKey(KeyEvent.KEYCODE_TV_INPUT);Thread.sleep(600);String path="/data/local/tmp/tvbuttons-inputs.xml";bridge.command("uiautomator","dump",path);String xml=bridge.command("cat",path);Matcher node=Pattern.compile("<node[^>]*text=\"HDMI"+port+"\"[^>]*bounds=\"\\[(\\d+),(\\d+)\\]\\[(\\d+),(\\d+)\\]\"").matcher(xml);if(!node.find())throw new java.io.IOException("HDMI input missing");int cx=(Integer.parseInt(node.group(1))+Integer.parseInt(node.group(3)))/2,cy=(Integer.parseInt(node.group(2))+Integer.parseInt(node.group(4)))/2;check(bridge.command("input","tap",""+cx,""+cy));return;}
  if(a.equals("inputs")){tapKey(KeyEvent.KEYCODE_TV_INPUT);return;}
  if(a.equals("screenshot")){String file="/sdcard/Pictures/TVButtons/TV-"+new java.text.SimpleDateFormat("yyyyMMdd-HHmmss",java.util.Locale.ROOT).format(new java.util.Date())+".png";bridge.command("mkdir","-p","/sdcard/Pictures/TVButtons");String result=bridge.command("screencap","-p",file);if(!result.trim().isEmpty())throw new java.io.IOException(result);bridge.message("Скриншот сохранён в Pictures/TVButtons");return;}
  if(a.equals("sleep")){tapKey(KeyEvent.KEYCODE_SLEEP);return;}
  if(a.equals("mouse")){synchronized(bridge){mouse=!mouse;if(mouse){x=bridge.config.optInt("width",1920)/2;y=bridge.config.optInt("height",1080)/2;bridge.ui("cursor:"+x+","+y);bridge.message("Мышь: стрелки — движение, OK — клик, Назад — выход");}else bridge.ui("cursoroff");bridge.configure(bridge.config);}return;}
  if(a.equals("black")){synchronized(bridge){black=!black;bridge.ui("black");}return;}
  if(a.equals("clock")||a.startsWith("timer:")||a.equals("canceltimer")){bridge.ui(a);return;}
  if(a.equals("scrollup")||a.equals("scrolldown")){int w=bridge.config.optInt("width",1920),h=bridge.config.optInt("height",1080);int from=a.equals("scrollup")?h/3:2*h/3,to=a.equals("scrollup")?2*h/3:h/3;check(bridge.command("input","swipe",""+(w/2),""+from,""+(w/2),""+to,"300"));return;}
  if(a.startsWith("link:")){String uri=new String(Base64.decode(a.substring(5),Base64.NO_WRAP),java.nio.charset.StandardCharsets.UTF_8);if(!uri.startsWith("https://")&&!uri.startsWith("http://"))throw new IllegalArgumentException();check(bridge.command("am","start","-a","android.intent.action.VIEW","-d",uri));return;}
  if(a.startsWith("macro:")){JSONArray steps=new JSONArray(new String(Base64.decode(a.substring(6),Base64.NO_WRAP),java.nio.charset.StandardCharsets.UTF_8));if(steps.length()>20)throw new IllegalArgumentException();for(int i=0;i<steps.length();i++){String step=steps.getString(i);if(step.startsWith("macro:"))throw new IllegalArgumentException();if(step.startsWith("delay:")){int ms=Integer.parseInt(step.substring(6));if(ms<0||ms>30000)throw new IllegalArgumentException();Thread.sleep(ms);}else if(step.startsWith("app:"))bridge.launchApp(step.substring(4));else if(isBasicKey(step))bridge.execute(step);else run(step);}return;}
  throw new IllegalArgumentException("Unknown action");
 }
 boolean isBasicKey(String a){return java.util.Arrays.asList("power","none","home","back","recents","volup","voldown","mute","play","next","prev","ff","rewind","channelup","channeldown").contains(a);}
 void start(String action)throws Exception {check(bridge.command("am","start","-a",action));}
 void component(String component)throws Exception {check(bridge.command("am","start","-n",component));}
 void check(String text)throws Exception {if(text.contains("Error:")||text.contains("Exception"))throw new java.io.IOException(text);}
 void tapKey(int key)throws Exception {synchronized(bridge){bridge.forward(key,1);bridge.forward(key,0);}}
 boolean mouseEvent(int key,int value)throws Exception {if(black&&key==KeyEvent.KEYCODE_BACK){if(value==0){black=false;bridge.ui("blackoff");}return true;}if(!mouse)return false;if(key==KeyEvent.KEYCODE_BACK){if(value==0){mouse=false;bridge.ui("cursoroff");bridge.configure(bridge.config);}return true;}if(key==KeyEvent.KEYCODE_DPAD_CENTER||key==KeyEvent.KEYCODE_ENTER){if(value==0)click();return true;}int w=bridge.config.optInt("width",1920),h=bridge.config.optInt("height",1080);if(key==19||key==20||key==21||key==22){if(value!=0){int delta=value==2?30:18;if(key==19)y-=delta;if(key==20)y+=delta;if(key==21)x-=delta;if(key==22)x+=delta;x=Math.max(0,Math.min(w-1,x));y=Math.max(0,Math.min(h-1,y));bridge.ui("cursor:"+x+","+y);}return true;}return false;}
 void click()throws Exception {long now=SystemClock.uptimeMillis();for(int action:new int[]{MotionEvent.ACTION_DOWN,MotionEvent.ACTION_UP}){MotionEvent e=MotionEvent.obtain(now,SystemClock.uptimeMillis(),action,x,y,0);e.setSource(InputDevice.SOURCE_TOUCHSCREEN);boolean ok=(Boolean)bridge.inject.invoke(bridge.input,e,0);e.recycle();if(!ok)throw new java.io.IOException("Tap refused");}}
 void close(){jobs.shutdownNow();history.shutdownNow();}
}
