package org.tvbuttons.free;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.view.*;import android.widget.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import java.util.*;
public class MainActivity extends Activity {
 public static volatile boolean screenActive;
 Handler statusHandler=new Handler();Runnable refresh=new Runnable(){public void run(){if(!capture)updateStatus();statusHandler.postDelayed(this,1000);}};
 android.content.SharedPreferences prefs;LinearLayout root;TextView status;Button adbButton;boolean capture;int selected=-1;
 public void onCreate(Bundle b){super.onCreate(b);screenActive=true;ControlMode.initialize(this);prefs=getSharedPreferences("buttons",0);render();ensureControl();statusHandler.post(refresh);}
 void ensureControl(){ControlMode.reconcile(this);}
 protected void onResume(){super.onResume();screenActive=true;ensureControl();if(AdbBridgeService.instance!=null)AdbBridgeService.instance.visible(true);updateStatus();}
 void updateStatus(){if(status!=null)status.setText(!ControlMode.enabled(this)?"Управление пультом выключено":ControlMode.adb(this)?AdbBridgeService.instance!=null?AdbBridgeService.state:"Подключаем управление через ADB…":MapperService.instance!=null?"Без ADB • служба специальных возможностей подключена":"Без ADB • включи службу «ТВ Кнопки» в специальных возможностях");if(adbButton!=null)adbButton.setText(prefs.getBoolean("enabled",true)?"Выключить управление пультом":"Включить управление пультом");}
 void chooseMode(){new AlertDialog.Builder(this).setTitle("Как управлять пультом?").setSingleChoiceItems(new String[]{"Через ADB — расширенные возможности","Без ADB — специальные возможности"},ControlMode.adb(this)?0:1,(d,n)->{prefs.edit().putString("control_mode",n==0?ControlMode.ADB:ControlMode.ACCESSIBILITY).apply();ensureControl();render();d.dismiss();}).setNegativeButton("Отмена",null).show();}
 void accessibilitySettings(){new AlertDialog.Builder(this).setTitle("Включи службу «ТВ Кнопки»").setMessage("В настройках Android открой «Специальные возможности» → «ТВ Кнопки» и включи службу. Она получает нажатия пульта; для мыши, прокрутки и выбора HDMI использует элементы экрана. Скриншоты создаются только по назначенной команде. Данные экрана никуда не отправляются. Службу можно отключить в тех же настройках. Если прошивка ТВ скрывает или блокирует сторонние службы, этот режим на нём включить не получится.").setPositiveButton("Открыть настройки",(d,n)->{Intent[] options={new Intent("android.settings.ACCESSIBILITY_DETAILS_SETTINGS").putExtra("android.intent.extra.COMPONENT_NAME",new ComponentName(this,MapperService.class)),new Intent(android.provider.Settings.ACTION_ACCESSIBILITY_SETTINGS),new Intent().setComponent(new ComponentName("com.android.tv.settings","com.android.tv.settings.accessibility.AccessibilityActivity")),new Intent(android.provider.Settings.ACTION_SETTINGS)};for(Intent i:options)try{startActivity(i);return;}catch(RuntimeException ignored){}Toast.makeText(this,"Открой специальные возможности через настройки ТВ",Toast.LENGTH_LONG).show();}).setNegativeButton("Отмена",null).show();}
 String actionTitle(String a){if(!ControlMode.adb(this)&&(a.equals("power")||a.equals("sleep")))return "Выключить экран (сон)";return ActionCatalog.label(a);}
 String limitation(String a){return ControlMode.adb(this)?"":MapperService.instance!=null?MapperService.instance.actions.limitation(a):AccessibilityActions.platformLimitation(this,a);}
 void acceptAction(String a,java.util.function.Consumer<String> picked){String reason=limitation(a);if(!reason.isEmpty()){Toast.makeText(this,reason,Toast.LENGTH_LONG).show();return;}picked.accept(a);}

 TextView text(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.WHITE);t.setPadding(12,10,12,10);root.addView(t);return t;}
 GradientDrawable bg(int c,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(14);d.setStroke(2,stroke);return d;}
 void button(String title,Runnable action){Button b=new Button(this);b.setText(title);b.setAllCaps(false);b.setTextSize(18);b.setTextColor(Color.WHITE);b.setGravity(Gravity.CENTER_VERTICAL|Gravity.LEFT);b.setPadding(24,0,24,0);b.setBackgroundTintList(null);b.setBackground(bg(0xff202c3c,0xff34465a));if(title.contains("\n")){b.setPadding(24,14,24,14);b.setMinHeight(96);}LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,title.contains("\n")?-2:72);lp.setMargins(0,0,0,12);root.addView(b,lp);b.setOnClickListener(v->action.run());b.setOnFocusChangeListener((v,f)->{b.setTextColor(f?0xff0a1921:Color.WHITE);b.setBackground(bg(f?0xff79dfc9:0xff202c3c,f?0xffa4f8e5:0xff34465a));});}
 protected void onPause(){screenActive=false;if(AdbBridgeService.instance!=null)AdbBridgeService.instance.visible(false);super.onPause();}
 void render(){ScrollView scroll=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(1);root.setPadding(72,32,72,32);root.setBackgroundColor(Color.rgb(13,20,30));scroll.addView(root);setContentView(scroll);status=text("",17);status.setTextColor(0xff92b7cb);
 button(prefs.getBoolean("enabled",true)?"Выключить управление пультом":"Включить управление пультом",()->{boolean enabled=!prefs.getBoolean("enabled",true);prefs.edit().putBoolean("enabled",enabled).apply();if(enabled)ensureControl();else stopService(new Intent(this,AdbBridgeService.class));updateStatus();});
 adbButton=(Button)root.getChildAt(1);
 button(ControlMode.adb(this)?"Режим: через ADB":"Режим: без ADB",this::chooseMode);
 if(!ControlMode.adb(this)){button("Включить службу / специальные возможности",this::accessibilitySettings);text("Android передаёт службе не все кнопки. Штатная кнопка питания сохраняется; назначение питания переводит экран в сон. Действия с пометкой «ADB» доступны в другом режиме.",15);}
 button("＋  Добавить кнопку",()->{capture=true;status.setText("Нажми кнопку пульта. «Назад» отменяет выбор.");});

 TreeSet<Integer> keys=new TreeSet<>();for(String k:prefs.getAll().keySet())if(k.startsWith("map."))try{keys.add(Integer.parseInt(k.split("\\.")[1]));}catch(Exception ignored){}
 text("Назначенные кнопки",23);if(keys.isEmpty())text("Пока нет назначений",17);for(int code:keys)button(mappingTitle(code),()->edit(code));updateStatus();}
 protected void onDestroy(){statusHandler.removeCallbacks(refresh);super.onDestroy();}
 public boolean dispatchKeyEvent(KeyEvent e){if(capture){if(e.getAction()==KeyEvent.ACTION_DOWN&&e.getRepeatCount()==0){capture=false;if(e.getKeyCode()!=KeyEvent.KEYCODE_BACK){if(e.getScanCode()>0){android.view.InputDevice device=e.getDevice();android.content.SharedPreferences.Editor edit=prefs.edit().putInt("scan."+e.getScanCode(),e.getKeyCode());if(device!=null&&!device.isVirtual())edit.putString("remote_device",device.getName());else edit.putString("remote_device","Virtual");edit.apply();}edit(e.getKeyCode());}else updateStatus();}return true;}return super.dispatchKeyEvent(e);}
 String keyLabel(int code){if(code>=KeyEvent.KEYCODE_0&&code<=KeyEvent.KEYCODE_9)return "Кнопка «"+(code-KeyEvent.KEYCODE_0)+"»";switch(code){case KeyEvent.KEYCODE_DPAD_UP:return "Стрелка вверх";case KeyEvent.KEYCODE_DPAD_DOWN:return "Стрелка вниз";case KeyEvent.KEYCODE_DPAD_LEFT:return "Стрелка влево";case KeyEvent.KEYCODE_DPAD_RIGHT:return "Стрелка вправо";case KeyEvent.KEYCODE_DPAD_CENTER:case KeyEvent.KEYCODE_ENTER:return "Кнопка OK";case KeyEvent.KEYCODE_BACK:return "Кнопка «Назад»";case KeyEvent.KEYCODE_HOME:return "Кнопка «Домой»";case KeyEvent.KEYCODE_MENU:return "Кнопка меню";case KeyEvent.KEYCODE_VOLUME_UP:return "Громкость +";case KeyEvent.KEYCODE_VOLUME_DOWN:return "Громкость −";case KeyEvent.KEYCODE_VOLUME_MUTE:return "Отключение звука";case KeyEvent.KEYCODE_CHANNEL_UP:return "Следующий канал";case KeyEvent.KEYCODE_CHANNEL_DOWN:return "Предыдущий канал";case KeyEvent.KEYCODE_PROG_RED:return "Красная кнопка";case KeyEvent.KEYCODE_PROG_GREEN:return "Зелёная кнопка";case KeyEvent.KEYCODE_PROG_YELLOW:return "Жёлтая кнопка";case KeyEvent.KEYCODE_PROG_BLUE:return "Синяя кнопка";case KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE:return "Пауза / воспроизведение";default:return "Кнопка № "+code;}}
 String actionLabel(String action){if(action.startsWith("app:")){if(action.equals("app:mobi.zona"))return "Zona";try{return getPackageManager().getApplicationLabel(getPackageManager().getApplicationInfo(action.substring(4),0)).toString();}catch(PackageManager.NameNotFoundException e){return "Приложение недоступно — выбери другое";}}if(!action.equals("panel"))return actionTitle(action)+(limitation(action).isEmpty()?"":" · нужен ADB / другая версия Android");switch(action){case "none":return "Ничего не делать";case "home":return "Домой";case "back":return "Назад";case "recents":return "Недавние приложения";case "volup":return "Увеличить громкость";case "voldown":return "Уменьшить громкость";case "mute":return "Отключить / включить звук";case "play":return "Пауза / воспроизведение";case "panel":return "Панель быстрых действий";case "":return "Не назначено";default:return "Выбери действие заново";}}
 String mappingTitle(int code){StringBuilder title=new StringBuilder(keyLabel(code)+" · "+KeyEvent.keyCodeToString(code));String[] gestures={"single","double","long"},labels={"Нажатие","Двойное","Долгое"};for(int i=0;i<gestures.length;i++){String action=prefs.getString("map."+code+"."+gestures[i],"");if(!action.isEmpty())title.append("\n").append(labels[i]).append(": ").append(actionLabel(action));}return title.toString();}
 void edit(int code){selected=code;String[] names={"Обычное: "+actionLabel(prefs.getString("map."+code+".single","")),"Двойное: "+actionLabel(prefs.getString("map."+code+".double","")),"Долгое: "+actionLabel(prefs.getString("map."+code+".long","")),"Удалить назначения этой кнопки"};new AlertDialog.Builder(this).setTitle(keyLabel(code)).setItems(names,(d,n)->{if(n==3){prefs.edit().remove("map."+code+".single").remove("map."+code+".double").remove("map."+code+".long").apply();render();}else choose(code,new String[]{"single","double","long"}[n]);}).show();}
 void choose(int code,String gesture){selectAction(action->{String key="map."+code+"."+gesture;if(action.equals("remove"))prefs.edit().remove(key).apply();else prefs.edit().putString(key,action).apply();render();},true);}
 void selectAction(java.util.function.Consumer<String> picked,boolean custom){java.util.ArrayList<String> choices=new java.util.ArrayList<>(java.util.Arrays.asList(ActionCatalog.BASIC));choices.add("app");choices.add("advanced");choices.add("remove");String[] titles=new String[choices.size()];for(int i=0;i<titles.length;i++){String a=choices.get(i);titles[i]=a.equals("app")?"Открыть приложение…":a.equals("advanced")?"Продвинутые действия…":a.equals("remove")?"Убрать назначение":actionTitle(a)+(limitation(a).isEmpty()?"":" · недоступно без ADB");}new AlertDialog.Builder(this).setTitle("Выбери действие").setItems(titles,(d,n)->{String a=choices.get(n);if(a.equals("app"))pickApp(picked);else if(a.equals("advanced"))advanced(picked,custom);else if(a.equals("inputs"))new AlertDialog.Builder(this).setTitle("Вход HDMI").setItems(new String[]{"Выбирать вход при нажатии","HDMI 1","HDMI 2","HDMI 3"},(dialog,port)->picked.accept(port==0?"inputs":"hdmi:"+port)).show();else acceptAction(a,picked);}).show();}
 void advanced(java.util.function.Consumer<String> picked,boolean allowMacro){java.util.ArrayList<String> actions=new java.util.ArrayList<>(java.util.Arrays.asList(ActionCatalog.ADVANCED));if(!allowMacro)actions.remove("macro");String[] labels=new String[actions.size()];for(int i=0;i<labels.length;i++)labels[i]=actionTitle(actions.get(i))+(limitation(actions.get(i)).isEmpty()?"":" · недоступно без ADB");new AlertDialog.Builder(this).setTitle("Продвинутые действия").setItems(labels,(d,n)->{String action=actions.get(n);if(action.equals("timer"))new AlertDialog.Builder(this).setTitle("Через сколько минут уснуть?").setItems(new String[]{"15 минут","30 минут","60 минут","90 минут","120 минут"},(dialog,i)->picked.accept("timer:"+new int[]{15,30,60,90,120}[i])).show();else if(action.equals("link"))link(picked);else if(action.equals("macro"))macro(new org.json.JSONArray(),picked);else acceptAction(action,picked);}).show();}
 void link(java.util.function.Consumer<String> picked){EditText input=new EditText(this);input.setSingleLine(true);input.setHint("https://…");input.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Адрес ссылки").setView(input).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{String uri=input.getText().toString().trim();if(!uri.startsWith("https://")&&!uri.startsWith("http://")){input.setError("Введи адрес с https:// или http://");return;}picked.accept("link:"+android.util.Base64.encodeToString(uri.getBytes(java.nio.charset.StandardCharsets.UTF_8),android.util.Base64.NO_WRAP));dialog.dismiss();}));dialog.show();}
 void macro(org.json.JSONArray steps,java.util.function.Consumer<String> picked){StringBuilder list=new StringBuilder();for(int i=0;i<steps.length();i++){String a=steps.optString(i);list.append(i+1).append(". ").append(a.startsWith("delay:")?"Пауза "+(Integer.parseInt(a.substring(6))/1000)+" с":actionLabel(a)).append("\n");}if(steps.length()==0)list.append("Добавь действия в нужном порядке. До 20 шагов.");new AlertDialog.Builder(this).setTitle("Макрос · "+steps.length()+" шагов").setMessage(list.toString()).setPositiveButton("Сохранить",(d,n)->{if(steps.length()>0)acceptAction("macro:"+android.util.Base64.encodeToString(steps.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8),android.util.Base64.NO_WRAP),picked);}).setNeutralButton("Добавить / изменить",(d,n)->new AlertDialog.Builder(this).setTitle("Шаг макроса").setItems(new String[]{"Добавить действие","Добавить паузу","Удалить последний шаг"},(dialog,i)->{if(i==2){if(steps.length()>0)steps.remove(steps.length()-1);macro(steps,picked);return;}if(steps.length()>=20){Toast.makeText(this,"Максимум 20 шагов",Toast.LENGTH_LONG).show();macro(steps,picked);return;}if(i==0)selectAction(a->{if(!a.equals("remove")){steps.put(a);}macro(steps,picked);},false);else new AlertDialog.Builder(this).setTitle("Пауза между действиями").setItems(new String[]{"1 с","2 с","5 с","10 с","30 с"},(wait,j)->{steps.put("delay:"+new int[]{1000,2000,5000,10000,30000}[j]);macro(steps,picked);}).show();}).show()).setNegativeButton("Отмена",null).show();}
 void pickApp(java.util.function.Consumer<String> picked){PackageManager pm=getPackageManager();TreeMap<String,String> items=new TreeMap<>();for(String category:new String[]{Intent.CATEGORY_LEANBACK_LAUNCHER,Intent.CATEGORY_LAUNCHER})for(ResolveInfo r:pm.queryIntentActivities(new Intent(Intent.ACTION_MAIN).addCategory(category),0)){String pkg=r.activityInfo.packageName;String label=pkg.equals("mobi.zona")?"Zona":r.loadLabel(pm).toString();String display=label;for(int suffix=2;items.containsKey(display)&&!items.get(display).equals(pkg);suffix++)display=label+" ("+suffix+")";items.put(display,pkg);}String[] labels=items.keySet().toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Приложение").setItems(labels,(d,n)->picked.accept("app:"+items.get(labels[n]))).show();}
}
