package org.tvbuttons.free;
import android.content.*;import android.graphics.*;import android.provider.Settings;import android.view.*;import android.widget.*;import android.os.*;
final class ScreenTools {
 final Context service;final boolean accessibility;final Handler handler=new Handler(Looper.getMainLooper());final WindowManager wm;View black,cursor;TextView clock;long deadline;
 final Runnable tick=new Runnable(){public void run(){if(clock!=null)clock.setText(new java.text.SimpleDateFormat("HH:mm",java.util.Locale.getDefault()).format(new java.util.Date()));handler.postDelayed(this,1000);}};
 final Runnable sleep;
 ScreenTools(AdbBridgeService s){this(s,false,a->{if(AdbBridgeService.instance==s)s.action(a);});}
 ScreenTools(Context s,boolean access,java.util.function.Consumer<String> execute){service=s;accessibility=access;sleep=()->{deadline=0;execute.accept("sleep");};wm=s.getSystemService(WindowManager.class);handler.post(tick);}
 void action(String a){handler.post(()->{try{if(a.startsWith("timer:")){int min=Integer.parseInt(a.substring(6));if(min<1||min>720)throw new IllegalArgumentException();handler.removeCallbacks(sleep);deadline=SystemClock.elapsedRealtime()+min*60000L;handler.postDelayed(sleep,min*60000L);toast("ТВ уснёт через "+min+" мин");return;}if(a.equals("canceltimer")){handler.removeCallbacks(sleep);deadline=0;toast("Таймер сна отменён");return;}if(!accessibility&&!Settings.canDrawOverlays(service)){toast("Разреши отображение поверх других приложений");return;}if(a.equals("black")){if(black!=null){remove(black);black=null;}else {black=new View(service);black.setBackgroundColor(Color.BLACK);wm.addView(black,params(-1,-1));toast("Чёрный экран: та же кнопка или «Назад» для выхода");}}else if(a.equals("clock")){if(clock!=null){remove(clock);clock=null;}else {clock=new TextView(service);clock.setTextColor(Color.WHITE);clock.setTextSize(28);clock.setPadding(18,8,18,8);clock.setBackgroundColor(0xb0182331);WindowManager.LayoutParams p=params(-2,-2);p.gravity=Gravity.TOP|Gravity.RIGHT;p.x=35;p.y=25;wm.addView(clock,p);}}else if(a.equals("blackoff")){remove(black);black=null;}else if(a.equals("cursoroff")){remove(cursor);cursor=null;}else if(a.startsWith("cursor:")){String[] xy=a.substring(7).split(",");if(cursor==null){cursor=new View(service){final Paint paint=new Paint(3);protected void onDraw(Canvas c){paint.setColor(Color.WHITE);c.drawCircle(16,16,11,paint);paint.setColor(0xff142c38);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(3);c.drawCircle(16,16,11,paint);paint.setStyle(Paint.Style.FILL);}};wm.addView(cursor,params(32,32));}WindowManager.LayoutParams p=params(32,32);p.x=Integer.parseInt(xy[0])-16;p.y=Integer.parseInt(xy[1])-16;wm.updateViewLayout(cursor,p);}}catch(Exception e){toast("Не удалось выполнить экранное действие");}});}
 WindowManager.LayoutParams params(int width,int height){WindowManager.LayoutParams p=new WindowManager.LayoutParams(width,height,accessibility?WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY:WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,PixelFormat.TRANSLUCENT);p.gravity=Gravity.TOP|Gravity.LEFT;return p;}
 void toast(String text){handler.post(()->Toast.makeText(service,text,Toast.LENGTH_LONG).show());}
 void remove(View v){if(v!=null)try{wm.removeView(v);}catch(Exception ignored){}}
 void close(){handler.removeCallbacksAndMessages(null);remove(black);remove(clock);remove(cursor);black=null;clock=null;cursor=null;}
}
