package org.tvbuttons.free;
import android.net.*;import android.os.*;import android.view.*;import org.json.*;import java.io.*;import java.lang.reflect.*;import java.nio.*;import java.util.*;import java.util.concurrent.*;
/** Runs as ADB shell, never invokes su. One authenticated app UID may connect. */
public final class ShellBridge {
 static final String SOCKET="tvbuttons.shell.bridge.v3";
 final BridgeActions advanced;
 final int appUid; final Map<Integer,Integer> keys=new HashMap<>(); final Map<Integer,Long> downs=new HashMap<>();
 final ScheduledExecutorService timer=Executors.newSingleThreadScheduledExecutor();
 final Map<Integer,ScheduledFuture<?>> holds=new HashMap<>(), doubles=new HashMap<>(); final Set<Integer> fired=new HashSet<>();
 String devicePath="/dev/input/event0",deviceName="input_btrcu";
 String eventsPath="/data/local/tmp/tvbuttons-events";boolean testing;final List<String> testActions=new ArrayList<>();
 final Object input; final Method inject; volatile JSONObject config=new JSONObject(); final Map<String,java.lang.Process> readers=new HashMap<>(); volatile PrintWriter out; volatile boolean capture=false; volatile boolean session=false;
 ShellBridge(int uid)throws Exception {appUid=uid;Class<?> c=Class.forName("android.hardware.input.InputManager");input=c.getMethod("getInstance").invoke(null);inject=c.getMethod("injectInputEvent",InputEvent.class,int.class);
  try(BufferedReader r=new BufferedReader(new FileReader("/vendor/usr/keylayout/Vendor_0001_Product_0001.kl"))){String s;while((s=r.readLine())!=null){String[] a=s.trim().split("\\s+");if(a.length>=3&&a[0].equals("key")){try{int k=KeyEvent.keyCodeFromString("KEYCODE_"+a[2]);if(k!=KeyEvent.KEYCODE_UNKNOWN)keys.put(Integer.parseInt(a[1]),k);}catch(Exception ignored){}}}}
  advanced=new BridgeActions(this);
 }
 public static void main(String[] args)throws Exception {if(android.os.Process.myUid()!=2000)throw new SecurityException("Start with ordinary ADB shell, not root");ShellBridge b=new ShellBridge(Integer.parseInt(args[0]));if(args.length>2&&args[1].equals("--events"))b.eventsPath=args[2];if(args.length>2&&args[1].equals("--test-action")){b.advanced.run(args[2]);b.advanced.close();b.timer.shutdownNow();return;}if(args.length>1&&args[1].equals("--self-test")){b.selfTest();b.timer.shutdownNow();b.advanced.close();return;}try(LocalServerSocket server=new LocalServerSocket(SOCKET)){try(FileWriter pid=new FileWriter("/data/local/tmp/tvbuttons-bridge.pid")){pid.write(""+android.os.Process.myPid());}System.out.println("READY uid=2000");while(true){try(LocalSocket s=server.accept()){if(s.getPeerCredentials().getUid()!=b.appUid)continue;b.session=true;b.out=new PrintWriter(s.getOutputStream(),true);b.status("CONNECTED");BufferedReader r=new BufferedReader(new InputStreamReader(s.getInputStream(),"UTF-8"));String line;while((line=r.readLine())!=null){JSONObject next=new JSONObject(line);if(next.has("action")){b.execute(next.getString("action"));continue;}b.configure(next);}}catch(Exception e){System.err.println("Session ended: "+e.getClass().getSimpleName());}finally{b.session=false;b.stopReader();b.out=null;}}}}
 synchronized void status(String s){System.out.println("STATUS "+s);if(out!=null)try{out.println(new JSONObject().put("status",s).toString());}catch(Exception ignored){}}
 synchronized void configure(JSONObject c){config=c;boolean want=c.optBoolean("enabled")&&!c.optBoolean("uiVisible")&&c.optJSONObject("maps")!=null&&(c.optJSONObject("maps").length()>0||advanced.mouse||advanced.black);if(readers.isEmpty()||want!=capture){stopReader();capture=want;startReaders();}if(!readers.isEmpty())status(capture?"ACTIVE":"OBSERVING");}
 synchronized void stopReader(){for(java.lang.Process process:readers.values())process.destroy();readers.clear();for(ScheduledFuture<?> f:holds.values())f.cancel(false);for(ScheduledFuture<?> f:doubles.values())f.cancel(false);holds.clear();doubles.clear();fired.clear();downs.clear();}
 void startReaders(){Set<String> names=new LinkedHashSet<>(Arrays.asList("input_btrcu","ir_keypad","ir_keypad1"));String saved=config.optString("deviceName");if(!saved.isEmpty()&&!saved.equals("Virtual"))names.add(saved);for(String name:names){try{selectDevice(name);startReader(devicePath,name,new HashMap<>(keys));}catch(Exception e){System.err.println("Input skipped: "+name+": "+e.getMessage());}}if(readers.isEmpty())status("ERROR: no remote input available; remote released");}
 void startReader(String path,String name,Map<Integer,Integer> layout){try{final java.lang.Process process=new ProcessBuilder(eventsPath,path,capture?"1":"0").start();readers.put(path,process);System.out.println("INPUT "+name+" "+path+" capture="+capture);new Thread(()->{try(DataInputStream in=new DataInputStream(process.getInputStream())){byte[] head=new byte[8];in.readFully(head);long result=ByteBuffer.wrap(head).order(ByteOrder.LITTLE_ENDIAN).getLong();if(result<0)throw new IOException("open/grab errno "+result);byte[] bytes=new byte[24];while(session){in.readFully(bytes);ByteBuffer x=ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN);int type=x.getShort(16)&65535,scan=x.getShort(18)&65535,value=x.getInt(20);synchronized(this){if(readers.get(path)!=process)return;if(type==1)event(scan,value,layout,name);}}}catch(Exception e){synchronized(this){if(readers.get(path)==process){stopReader();status("ERROR: "+name+": "+e.getMessage()+"; remote released");}}}},"evdev-"+name).start();}catch(Exception e){status("ERROR: "+name+": "+e.getMessage());}}
 synchronized void event(int scan,int value)throws Exception {event(scan,value,keys,"self-test");}
 synchronized void event(int scan,int value,Map<Integer,Integer> layout,String source)throws Exception {System.out.println("EVENT source="+source+" scan="+scan+" value="+value+" capture="+capture);Integer key=layout.get(scan);JSONObject scanMap=config.optJSONObject("scans");if(key==null&&scanMap!=null&&scanMap.has(""+scan))key=scanMap.getInt(""+scan);if(out!=null)out.println(new JSONObject().put("source",source).put("scan",scan).put("key",key==null?-1:key).put("value",value).toString());if(!capture)return;if(key==null){stopReader();status("ERROR: unknown scan "+scan+"; remote released");return;}if(advanced.mouseEvent(key,value))return;JSONObject maps=config.optJSONObject("maps");JSONObject actions=maps==null?null:maps.optJSONObject(""+key);if(key==KeyEvent.KEYCODE_POWER)actions=null;if(actions==null){forward(key,value);return;}
 String single=actions.optString("single"),dbl=actions.optString("double"),lng=actions.optString("long");final int k=key;
 if(value==1){downs.put(k,SystemClock.uptimeMillis());fired.remove(k);if(!lng.isEmpty())holds.put(k,timer.schedule(()->{synchronized(this){if(!downs.containsKey(k))return;fired.add(k);ScheduledFuture<?> f=doubles.remove(k);if(f!=null)f.cancel(false);try{execute(lng);}catch(Exception e){status("ERROR: action failed");}}},650,TimeUnit.MILLISECONDS));}
 else if(value==0){downs.remove(k);ScheduledFuture<?> h=holds.remove(k);if(h!=null)h.cancel(false);if(fired.remove(k))return;if(!dbl.isEmpty()){ScheduledFuture<?> pending=doubles.remove(k);if(pending!=null){pending.cancel(false);execute(dbl);}else doubles.put(k,timer.schedule(()->{synchronized(this){doubles.remove(k);try{execute(single);}catch(Exception e){status("ERROR: action failed");}}},300,TimeUnit.MILLISECONDS));}else execute(single);}
 }
 synchronized void forward(int key,int value)throws Exception {long now=SystemClock.uptimeMillis();if(value==1)downs.put(key,now);long down=downs.getOrDefault(key,now);KeyEvent event=new KeyEvent(down,now,value==0?KeyEvent.ACTION_UP:KeyEvent.ACTION_DOWN,key,value==2?1:0,0,KeyCharacterMap.VIRTUAL_KEYBOARD,0,KeyEvent.FLAG_FROM_SYSTEM,InputDevice.SOURCE_KEYBOARD);boolean ok=(Boolean)inject.invoke(input,event,0);if(value==0)downs.remove(key);if(!ok)throw new IOException("input injection refused");}
 synchronized void execute(String a)throws Exception {if(testing){if(!a.isEmpty())testActions.add(a);return;}int key;switch(a){case "":case "none":return;case "power":key=26;break;case "home":key=3;break;case "back":key=4;break;case "recents":key=187;break;case "volup":key=24;break;case "voldown":key=25;break;case "mute":key=164;break;case "play":key=85;break;case "next":key=87;break;case "prev":key=88;break;case "ff":key=90;break;case "rewind":key=89;break;case "channelup":key=166;break;case "channeldown":key=167;break;default:if(a.startsWith("app:")){final String pkg=a.substring(4);new Thread(()->{try{launchApp(pkg);}catch(Exception e){System.err.println("Launch failed: "+pkg+": "+e);status("ERROR: application launch failed");}},"launch-app").start();}else advanced.submit(a);return;}forward(key,1);forward(key,0);}
 synchronized void ui(String action){if(out!=null)try{out.println(new JSONObject().put("uiAction",action));}catch(Exception ignored){}}
 synchronized void message(String text){if(out!=null)try{out.println(new JSONObject().put("message",text));}catch(Exception ignored){}}
 String command(String... args)throws Exception {java.lang.Process process=new ProcessBuilder(args).redirectErrorStream(true).start();StringBuilder result=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(process.getInputStream(),"UTF-8"))){String line;while((line=r.readLine())!=null)result.append(line).append('\n');}process.waitFor();return result.toString();}
 void launchApp(String pkg)throws Exception {for(String category:new String[]{"android.intent.category.LEANBACK_LAUNCHER","android.intent.category.LAUNCHER"}){String resolved=command("cmd","package","resolve-activity","--brief","--user","0","-a","android.intent.action.MAIN","-c",category,"-p",pkg);for(String line:resolved.split("\n")){String component=line.trim();if(!component.startsWith(pkg+"/"))continue;String result=command("am","start","--user","0","-a","android.intent.action.MAIN","-c",category,"-n",component);System.out.println("LAUNCH "+component+": "+result.trim());if(!result.contains("Error:")&&!result.contains("Exception"))return;}}throw new IOException("No launchable activity for "+pkg);}
 void selfTest()throws Exception {
  forward(KeyEvent.KEYCODE_UNKNOWN,1);forward(KeyEvent.KEYCODE_UNKNOWN,0);System.out.println("PASS shell input injection");
  testing=true;capture=true;JSONObject maps=new JSONObject(),row=new JSONObject().put("single","single");maps.put("8",row);config=new JSONObject().put("maps",maps);
  event(2,1);event(2,0);if(!testActions.equals(Arrays.asList("single")))throw new AssertionError("single");testActions.clear();
  row.put("double","double");event(2,1);event(2,0);Thread.sleep(40);event(2,1);event(2,0);Thread.sleep(350);if(!testActions.equals(Arrays.asList("double")))throw new AssertionError("double");testActions.clear();
  row.put("long","long");event(2,1);Thread.sleep(750);event(2,0);Thread.sleep(350);if(!testActions.equals(Arrays.asList("long")))throw new AssertionError("long");testActions.clear();
  event(2,1);event(2,0);Thread.sleep(350);if(!testActions.equals(Arrays.asList("single")))throw new AssertionError("delayed single");
  System.out.println("PASS single, double, long, delayed single");
 }

 String readFile(File f)throws IOException {try(BufferedReader r=new BufferedReader(new FileReader(f))){return r.readLine().trim();}}
 void selectDevice(String name)throws Exception {File[] entries=new File("/sys/class/input").listFiles();if(entries!=null)for(File entry:entries){if(!entry.getName().startsWith("event"))continue;File dev=new File(entry,"device");if(!readFile(new File(dev,"name")).equals(name))continue;String vendor=readFile(new File(dev,"id/vendor")),product=readFile(new File(dev,"id/product"));String filename="Vendor_"+vendor+"_Product_"+product+".kl";File layout=new File("/vendor/usr/keylayout",filename);if(!layout.isFile())layout=new File("/system/usr/keylayout",filename);if(!layout.isFile())layout=new File("/vendor/usr/keylayout/Generic.kl");if(!layout.isFile())layout=new File("/system/usr/keylayout/Generic.kl");keys.clear();try(BufferedReader r=new BufferedReader(new FileReader(layout))){String line;while((line=r.readLine())!=null){String[] a=line.trim().split("\\s+");if(a.length>=3&&a[0].equals("key")){try{int k=KeyEvent.keyCodeFromString("KEYCODE_"+a[2]);if(k!=KeyEvent.KEYCODE_UNKNOWN)keys.put(Integer.decode(a[1]),k);}catch(Exception ignored){}}}}deviceName=name;devicePath="/dev/input/"+entry.getName();return;}throw new IOException("No input device");}

}
