plugins { id 'com.android.application' }
android { namespace 'org.tvbuttons.free'; compileSdk 35; defaultConfig { applicationId 'org.tvbuttons.free'; minSdk 26; targetSdk 32; versionCode 13; versionName '0.3.0'; testInstrumentationRunner 'org.tvbuttons.free.BackendTest' }; compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 } }

tasks.withType(JavaCompile).configureEach { options.encoding = "UTF-8" }
